### ISSUE TITLE
Redist.py doesn't handle 32bit VisualStudio installed on a 64bit system

### ISSUE THREAD

**Issue by Reavenk** [PrimeSense/Sensor#1]
In the script, it's hardcoded to HKLM\Software\Microsoft\VisualStudio\10.0\InstallDir instead of HKLM\Wow6432Node\Software\Microsoft\VisualStudio\10.0\InstallDir for me.

http://social.msdn.microsoft.com/Forums/en/vsxprerelease/thread/3d38070a-2b61-489d-b3f9-c1c9595176d0

**Comment by OpenNI** [comment]
Fixed in Sensor 5.1 and above.
